---
dotvim: "~/.vim"
downloads: "~/.ansible-downloads"
ohmyzsh_install_dir: "~/.oh-my-zsh"
sublime_userdir: "~/Library/Application Support/Sublime Text 3/Packages/User"
sublime_packagedir: "~/Library/Application Support/Sublime Text 3/Installed Packages"
dockutil_install_path: "/usr/local/bin/dockutil"
macos_version: 10.15.2


osx_script: "~/.macos --no-restart"

configure_dotfiles: yes
configure_iterm: yes
configure_osx: yes
configure_sudoers: yes
configure_terminal: yes
configure_vim: yes
configure_ohmyzsh: yes
configure_sublimetext: yes
configure_dock: yes

dotfiles_repo: https://github.com/amatos/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_files:
  - .aliases
  # - .bash_profile
  # - .bash_prompt
  # - .bashrc
  - .curlrc
  - .editorconfig
  - .exports
  - .functions
  - .gdbinit
  - .gitattributes
  - .gitconfig
  - .gitignore
  # - .gvimrc
  # - .hgignore
  - .hushlogin
  - .inputrc
  - .macos
  # - .osx
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .wgetrc
  - .zshrc

homebrew_installed_packages:
  # - autoconf
  # - bash-completion
  # - coreutils
  # - doxygen
  # - findutils
  # - gettext
  # - gifsicle
  # - go
  # - iperf
  # - libevent
  # - mcrypt
  # - moreutils
  # - node
  # - nvm
  # - openssl
  # - php
  # - bash
  # - bash-completion2
  # - cowsay
  # - git
  # - gnu-sed
  # - gpg
  # - grep
  # - imagemagick
  # - pv
  # - readline
  # - sqlite
  # - ssh-copy-id
  # - vim
  # - wrk
  # - zsh
  # - zsh-autosuggestions
  # - zsh-completions
  # - zsh-syntax-highlighting
  - dockutil
  - duti
  - httpie
  - hub
  - mas
  - nmap
  - node
  - wget
  - yarn

homebrew_taps:
  - bramstein/webfonttools
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - chromedriver
  # - firefox
  # - handbrake
  # - licecap
  # - macvim
  # - mysides
  # - qlcolorcode
  # - qlimagesize
  # - qlmarkdown
  # - qlstephen
  # - qlvideo
  # - quicklook-json
  # - quicklookase
  # - sequel-pro
  # - skitch
  # - slack
  # - suspicious-package
  # - transmit
  # - vagrant
  - adguard
  - adobe-creative-cloud
  - aerial
  - alfred
  - calibre
  - docker
  - dropbox
  - droplr
  - google-chrome
  - google-drive-file-stream
  - google-earth-pro
  - gpg-suite
  - imazing
  - iterm2
  - kaleidoscope
  - scrivener
  - scroll-reverser
  - setapp
  - skype
  - sublime-merge
  - sublime-text
  - superduper
  - swiftdefaultappsprefpane
  - transmission

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_apps:
  - { name: "1Password", id: 1333542190 }
  - { name: "Affinity Designer", id: 824171161 }
  - { name: "Affinity Photo", id: 824183456 }
  - { name: "Bear", id: 1091189122 }
  - { name: "Browser Fairy", id: 483014855 }
  - { name: "Cardhop", id: 1290358394 }
  - { name: "CleanMyDrive 2", id: 523620159 }
  - { name: "Day One", id: 1055511498 }
  - { name: "Fantastical 2", id: 975937182 }
  - { name: "Front and Center", id: 1493996622 }
  - { name: "Keynote", id: 409183694 }
  - { name: "NepTunes for LastFm", id: 1006739057 }
  - { name: "Numbers", id: 409203825 }
  - { name: "OneDrive", id: 823766827 }
  - { name: "Pages", id: 409201541 }
  - { name: "PopClip", id: 445189367 }
  - { name: "Shazam", id: 897118787 }
  - { name: "Spark", id: 1176895641 }
  - { name: "Spillo", id: 873245660 }
  - { name: "Twitterrific", id: 1289378661 }
  - { name: "Videux Play LT", id: 1204104924 }
  - { name: "Xcode", id: 497799835 }

dockitems_remove_all: true

dockitems_enabled:
  - name: "Launchpad"
    path: "/System/Applications/Launchpad.app"
    pos: 1
  - name: "Safari"
    path: "/Applications/Safari.app"
    pos: 2
  - name: "Spark"
    path: "/Applications/Spark.app"
    pos: 3
  - name: "FaceTime"
    path: "/System/Applications/FaceTime.app"
    pos: 4
  - name: "Messages"
    path: "/System/Applications/Messages.app"
    pos: 5
  - name: "Photos"
    path: "/System/Applications/Photos.app"
    pos: 6
  - name: "Fantastical"
    path: "/Applications/Fantastical.app"
    pos: 7
  - name: "Bear"
    path: "/Applications/Bear.app"
    pos: 8
  - name: "Music"
    path: "/System/Applications/Music.app"
    pos: 9
  - name: "News"
    path: "/System/Applications/News.app"
    pos: 10
  - name: "App Store"
    path: "/System/Applications/App Store.app"
    pos: 11
  - name: "System Preferences"
    path: "/System/Applications/System Preferences.app"
    pos: 12
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app"
    pos: 13
  - name: "Sublime Merge"
    path: "/Applications/Sublime Merge.app"
    pos: 14
  - name: "iTerm"
    path: "/Applications/iTerm.app"
    pos: 15
  - name: "Downloads"
    path: "~/Downloads"
    pos: 16

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
