---
dotvim: ~/.vim
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_osx: yes
configure_sudoers: yes
configure_terminal: yes
configure_vim: yes

dotfiles_repo: https://github.com/amatos/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .exports
  - .functions
  - .gdbinit
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gvimrc
  - .hgignore
  - .hushlogin
  - .inputrc
  - .macos
  - .osx
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .wgetrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - coreutils
  # - doxygen
  # - findutils
  # - gettext
  # - gifsicle
  # - go
  # - iperf
  # - libevent
  # - mcrypt
  # - moreutils
  # - node
  # - nvm
  # - openssl
  # - php
  # - pv
  # - readline
  # - sqlite
  # - wget
  # - wrk
  # - { name: gnu-sed, install_options: "with-default-names" }
  - bash
  - bash-completion2
  - cowsay
  - git
  - gpg
  - grep
  - httpie
  - hub
  - mas
  - nmap
  - ssh-copy-id
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
  - { name: imagemagick, install_options: "with-webp" }
  - { name: vim, install_options: "with-luajit,override-system-vi" }
  - { name: wget, install_options: "with-iri" }

homebrew_taps:
  - bramstein/webfonttools
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - chromedriver
  # - docker
  # - dropbox
  # - firefox
  # - handbrake
  # - licecap
  # - macvim
  # - sequel-pro
  # - skitch
  # - slack
  # - sublime-text
  # - transmit
  # - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email:
mas_password:

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
