---
- name: Ensure ~/workarounds exists.
  file:
    path: {{ workarounds_dir }}
    state: directory
  register: workarounds_dir_exists

- name: copt apropos script, removing /usr/lib from apropos path
  command: "sed -e 66s@/usr/lib@@ /usr/bin/apropos > {{ workarounds_dir }}/apropos.{{ macos_version }}"
  when: workarounds_dir_exists
  register: apropos_workaround

- name: Change file ownership, group and permissions
  file:
    path: "{{ workarounds_dir }}/apropos.{{ macos_version }}"
    mode: '0755'
  when: apropos_workaround