---
- name: Copy apropos script to /usr/local/bin
  copy:
    src: /usr/bin/apropos
    dest: "/usr/local/bin/apropos.{{ macos_version }}"
    owner: "{{ lookup('env','USER') }}"
    group: 'staff'
    mode: '0755'
  register: copied_apropos

- name: Remove /usr/lib from apropos work-around script
  replace:
    path: "/usr/local/bin/apropos.{{ macos_version }}"
    regexp: '(for d in)( )(/var/cache/man)( )(\$manpath)(.*)'
    replace: '\1\2\3\4\5'
  when: copied_apropos
